travis:
  secure:
    BINSTAR_TOKEN: bFI0mApuziENE8AFJiMIqvjBIe8TOrEpEAQzhVaen58D+IoWXOSixtXXhd8PlZ6D/h/+mo/iKrGbsZk+wK3EjrF6OLgkRg0LUOCvsDJiMZ4EG5h0xekIyE8D6jz4Nvk6eCqL1fyM1bUlZ7LAsWWbsUi2CR9gKN4srkxre5tCzbTRks1CeiL2JzHsYayFR0PZ2eud8SHlyRIC/puwlIepokT3kXm2vZZkqNVBdm5yhiG7ZJn6pb8l3ztcEwtkhnEBsjEPDW1yOvKBkkjdXS6FyRCS8o0n4gmnE5mg0GgSfbODV+n14F1hslm7DFw619VsForbRrDH6Lt+ob8Jui/TF+f+DMU89ZD0pjTa0fYY9hHQ/fEO+YUBS8o8OjHIlbVeHwCS/+EnsYWslqEIOzPyyad/pyFNNFa/hVomloFV4C0mxu3n/meZz5Hmh79uPfMv3nkOxXP8rexHqfHSJabhi/5belJ48e0LbUyAr9hzFjP3fv12Xrc/GPw+wns6yo919BNnEF9wxoqML21GI3NoS2URvF0rq0beitJMTKVw+rjXRvyI4Sa0PSyyJlxjcXoNvP0C9NSApZhGPALr7ONf7nn9VMA7JbE08dbQEcCZWOX6lnWsTZBw7ogPSXbBBTbTs3DMzJGMy96/vFCGAHJCG3isvSU1T6ODoZILou1ewfo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
